# Set this website's info
# Change "coffeebank" to your GitHub username
# Change "moonrise" to your repository name
url: "https://discord.gg/ByxtBMaeTt"
baseurl: "https://discord.gg/ByxtBMaeTt"
siteIcon: /media/android-chrome-192x192.png
siteYear: 2020
siteFooterlink: /about
showinSearchEngines: true
# googleAnalyticsID: (uncomment to use)


# Set basic server info
serverName: AxolotlMC.pl
serverDescription: Serwer Minecraft, na którym świetnie się bawimy!
serverIP: play.axolotlmc.pl
useBedrockForOnlineStatus: false


# Discord information
discordInvite: https://discord.gg/ByxtBMaeTt
discordServerID: 857245994307813376
discordChannelID: 857245994307813376


# # Navbar Links at the top of the page (uncomment "siteNav" to use)
# #   name - The title on the navbar
# #   url - The link it should go to (for example, if you have "maps.md" file, put "maps")
# #   newtab - Whether link should open in new tab
# 
# siteNav:
#   - name: Server Map
#     url: map
#     newtab: true
#   - name: Screenshots
#     url: screenshots
#   - name: About
#     url: about


# Don't change anything below here, these are defaults set by GitHub Pages:
# ======
theme: jekyll-theme-slate
# plugins:
#   - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
